---
- name: Playbook to play with some time functions
  hosts: localhost
  gather_facts: false

  tasks:
     - name: 01 - Obtain the Current Date Time
       ansible.builtin.set_fact:
          current_date: "{{ ansible_date_time.iso8601 }}"

     - name: 01a - Debug current_date
       ansible.builtin.debug:
          msg:
             - "current_date is of type {{ current_date.__class__.__name__ }}"
             - "current_date value is {{ current_date }}"
             
     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play
       when: 1 == 1

     - name: 05b - Convert yaml to datetime object
       ansible.builtin.set_fact:
          expiry_date_datetime: "{{ expiry_date_yaml | to_datetime }}"

# sdfasd

