---
- name: Playbook to play with some time functions
  hosts: all
  gather_facts: true

  tasks:
     - name: 01 - Obtain the Current Date Time
       ansible.builtin.set_fact:
          current_date: "{{ ansible_date_time }}"


     - name: 01a - Debug
       debug:
          msg: 
            - "Fact text is {{ current_date.date }}"
            - "Class Name is {{ current_date.date.__class__.__name__ }}"


     - name: 02 - add 7 days to the current date
       ansible.builtin.set_fact:
         new_date: "{{ (current_date.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') + 7 * 86400) | to_datetime('%Y-%m-%d') | string }}"


     - name: 02a - Debug
       debug:
          msg: 
            - "Fact text is {{ new_date.date }}"
            - "Class Name is {{ new_date.date.__class__.__name__ }}"




     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play
       when: 1 == 1




################################################################################
################################################################################


################################################################################
################################################################################







