---
- name: Playbook to play with some time functions
  hosts: all
  gather_facts: true

  tasks:
     - name: 01 - Obtain the Current Date Time
       ansible.builtin.set_fact:
          current_date: "{{ ansible_date_time }}"

     - name: 02 - Debug current_date
       ansible.builtin.debug:
          msg:
             - "current_date is of type {{ current_date.__class__.__name__ }}"
             - "current_date value is {{ current_date }}"

     - name: 03 - Display the current timezone
       ansible.builtin.debug:
          msg: "Current timezone: {{ current_date.tz }}"

     - name: 04 - Display the current time in ISO 8601 Format
       debug:
          msg: "Current Time in ISO 8601 Format: {{ current_date.iso8601 }}"


     - name: 06 - Pipe native function to to_datetime
       ansible.builtin.set_fact:
          date_datetime: "{{ ansible_date_time | to_datetime }}"

     - name: 06a - Debug date_datetime
       ansible.builtin.debug:
          msg:
             - "date_datetime is of type {{ date_datetime.__class__.__name__ }}"
             - "date_datetime value is {{ date_datetime }}"




     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play
       when: 1 == 1




################################################################################
################################################################################


################################################################################
################################################################################







