---
- name: Playbook to play with some time functions
  hosts: all
  gather_facts: true

  tasks:
     - name: 01 - Obtain the Current Date Time
       ansible.builtin.set_fact:
          current_date: "{{ ansible_date_time }}"

     - name: 02 - Debug current_date
       ansible.builtin.debug:
          msg:
             - "current_date is of type {{ current_date.__class__.__name__ }}"
             - "current_date value is {{ current_date }}"

     - name: 03 - Display the current timezone
       ansible.builtin.debug:
         msg: "Current timezone: {{ current_date.tz }}"

     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play
       when: 1 == 1
