---
- name: Playbook to play with some time functions
  hosts: all
  gather_facts: true

  tasks:
     - name: 01 - Obtain the Current Date Time
       ansible.builtin.set_fact:
          current_time: "{{ ansible_date_time.time }}"

     - name: 01a - Debug current_date
       ansible.builtin.debug:
          msg:
             - "current_date is of type {{ current_date.__class__.__name__ }}"
             - "current_date value is {{ current_date }}"

     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play
       when: 1 == 1
