---
- name: Playbook to calculate time differences and format dates
  hosts: all
  gather_facts: false

  vars:
#    date1: '2022-11-15T03:23:13.6869568Z'
#    date2: '2021-12-15T16:06:24.400087Z'
#    date1_short: '{{ date1 | regex_replace("([^.]+)(\\.\\d{6})(\\d*)(.+)", "\\1\\2\\4") }}'
#    iso8601format: '%Y-%m-%dT%H:%M:%S.%fZ'

  tasks:

################################################################################
################################################################################

# when this is piped to to_datetime, it will be a str object
    - name: 01a - Get amount of days between two dates
      set_fact:
        fact: '{{ ("2024-08-11 13:00:00") }}'

    - name: 01b - Print the new fact
      debug:
        msg: "The fact is {{ fact }}"

    - name: 01c - Review the fact that was set
      debug:
        var: fact.__class__.__name__



################################################################################
################################################################################


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play
      when: 1 == 1





    - name: 01a - Calculate difference between dotnet and iso8601 microsecond timestamps
      set_fact:
        date_diff_isoed: '{{ (date1_short | to_datetime(iso8601format) - date2 | to_datetime(iso8601format)).total_seconds() }}'

    - name: 01b - Print difference between dotnet and iso8601 timestamps
      debug:
        msg: "Difference in seconds between date1 and date2 is {{ date_diff_isoed }} seconds"

    - name: 01c - Review the fact that was set
      debug:
        var: date_diff_isoed.__class__.__name__


