---
- name: Playbook to calculate time differences and format dates
  hosts: all
  gather_facts: true
  tasks:

################################################################################
################################################################################
# https://stackoverflow.com/questions/65520845/calculate-number-of-days-between-two-variable-one-a-set-variable-the-other-fro
    - name: 31 - Obtain the Current Date Time as a Function
      ansible.builtin.set_fact:
        sec1: "{{ ansible_date_time }}"

    - name: 31a - Print the dictionary based Time Fact
      ansible.builtin.debug:
          msg:
            - "The fact is {{ sec1 }}"
            - "fact type: {{ sec1 | type_debug }}"
            - "fact class: {{ sec1.__class__.__name__}}"

    - name: 31b - Create new variable to hold the seconds
      ansible.builtin.set_fact:
        sec1a: "{{ sec1.second | to_datetime('%S') }}"


    - name: 31c - Print the dictionary based Time Fact
      ansible.builtin.debug:
          msg:
            - "The fact is {{ sec1a }}"
            - "fact type: {{ sec1a | type_debug }}"
            - "fact class: {{ sec1a.__class__.__name__}}"


    - name: 32 - Pause the playbook for 5 seconds
      ansible.builtin.pause:
        seconds: 3

    - name: 33 - Gather facts again
      ansible.builtin.setup:

    - name: 34 - Obtain the Current Date Time as a Function
      ansible.builtin.set_fact:
        sec2: "{{ ansible_date_time }}"

    - name: 34 - Calculate difference between Today's Date and New Years Date
      ansible.builtin.set_fact:
        date_diff: "{{ ((sec2.second | to_datetime('%S')).second - (sec1.second | to_datetime('%S')).second) }}"

    - name: 36 - Print the dictionary based Time Fact
      ansible.builtin.debug:
          msg:
            - "The different between the two second variables {{ date_diff }}"
            - "fact type: {{ date_diff | type_debug }}"
            - "fact class: {{ date_diff.__class__.__name__}}"


################################################################################
################################################################################

    - name: 11 - Obtain the Current Date Time as a Function
      ansible.builtin.set_fact:
        dict: "{{ ansible_date_time }}"

    - name: 12 - Obtain the Current Date Time as a Function
      ansible.builtin.set_fact:
        date1: "{{ dict.date }}"

    - name: 13 - Obtain the Current Date Time as a Function
      ansible.builtin.set_fact:
        time1: "{{ dict.time }}"

    - name: 14 - concatenate date and time
      ansible.builtin.set_fact:
        current_date: "{{ date1 }} {{ time1 }}"

    - name: 15 - Print the dictionary based Time Fact
      ansible.builtin.debug:
          msg:
            - "The fact is {{ current_date }}"
            - "fact type: {{ current_date | type_debug }}"
            - "fact class: {{ current_date.__class__.__name__}}"


    - name: 20 - Obtain the Current Date Time as a Function
      ansible.builtin.set_fact:
        current_second11: "{{ ansible_date_time | to_datetime }}"

    - name: 30 - Calculate difference between Today's Date and New Years Date
      ansible.builtin.set_fact:
        date_diff: '{{ (current_second11.second) - (current_second10.second) }}'
#                   {{ ((ansible_date_time.date | to_datetime('%Y-%m-%d')).date() - prev_date).days }}


    - name: 40 - Print difference between Today's Date and New Years Date
      ansible.builtin.debug:
        msg: "Difference in seconds between date1 and date2 is {{ date_diff }} seconds"

    - name: 50 - Review the fact that was set
      ansible.builtin.debug:
        var: date_diff.__class__.__name__



