---
 - hosts: localhost
   tasks:
     - set_fact:
         time1: "{{ ansible_date_time }}"

     - set_fact:
         time1a: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"

#     - ansible.builtin.to_datetime:
#         time1a: "{{ time1a }}"
# dict    time1: "{{ ansible_date_time }}"
# failed  time1: "{{ ansible_date_time | to_datetime }}"
# AUT     time1: "{{ ansible_date_time.iso8601 }}"
# failed  time1: "{{ ansible_date_time.iso8601 | to_datetime }}"
# AUT     time1: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"
# failed  time1: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%d %H:%M:%S') }}"
# failed  time1: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') | to_datetime }}"
# failed  time1: "{{ ansible_date_time.iso8601 | to_datetime | to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"


     - debug:
         msg: 
         - "{{ time1a }}"
         - "{{ time1a | type_debug }}"

     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play
       when: 1 == 1


     - set_fact:
         time2: 2024-08-17T02:00:00Z

     - debug:
         msg: 
         - "{{ time2 }}"
         - "{{ time2 | type_debug }}"

#     - debug:
#         var: ( '2024-08-17T02:10:00Z'|to_datetime("%Y-%m-%dT%H:%M:%SZ") - '2024-08-17T02:00:00Z'|to_datetime("%Y-%m-%dT%H:%M:%SZ")).total_seconds()

     - debug:
         msg: "{{ time1 - time2 }}" 

