---
 - hosts: localhost
   tasks:
     - ansible.builtin.set_fact:
         time1: "{{ ansible_date_time.date }}"
#         time1: "{{ ansible_date_time.iso8601 | regex_replace('T.*', '') }}"
#         time1: "{{ ansible_date_time.iso8601 | replace('T', ' ') | replace('Z', ' ') }}"
#         time1: "{{ ansible_date_time.iso8601 | replace('T', ' ') | replace('Z', ' ') }}"



     - ansible.builtin.set_fact:
         time2: 2024-01-01T00:00:00Z

     - ansible.builtin.debug:
         msg: 
         - "{{ time1 }} {{ time1 | type_debug }}"
         - "{{ time2 }} {{ time2 | type_debug }}"



#     - debug:
#         var: ( '2024-08-17T02:10:00Z'|to_datetime("%Y-%m-%dT%H:%M:%SZ") - '2024-08-17T02:00:00Z'|to_datetime("%Y-%m-%dT%H:%M:%SZ")).total_seconds()


#     - debug:
#         msg: "{{ time1 - time2 }}" 




     - name: 08 - Calculate difference between expiry date and today
       set_fact:
         days_until_expiry: "{{ (time1 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) - (time2 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) }}"
#        days_until_expiry: "{{ (current_date | to_datetime("%Y-%m-%dT%H:%M:%SZ"))" - "(expiry_date | to_datetime("%Y-%m-%dT%H:%M:%SZ")) }}
 


     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play





#
#  All of these tasks failed for one reason or another
#
# dict    time1: "{{ ansible_date_time }}"
# failed  time1: "{{ ansible_date_time | to_datetime }}"
# AUT     time1: "{{ ansible_date_time.iso8601 }}"
# failed  time1: "{{ ansible_date_time.iso8601 | to_datetime }}"
# AUT     time1: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"
# failed  time1: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%d %H:%M:%S') }}"
# failed  time1: "{{ ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ') | to_datetime }}"
# failed  time1: "{{ ansible_date_time.iso8601 | to_datetime | to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"

