---
 - hosts: localhost
   tasks:
     - name: Create fact for time - fact will be AnsibleUnicode
       ansible.builtin.set_fact:
         time1: "2024-01-01"

     - name: Create fact for time - fact will be AnsibleUnicode
       ansible.builtin.set_fact:
         time2: "2024-02-01"
    

     - name: Calculate difference between dates
       set_fact:
         diff: "{{ (time2 | to_datetime('%Y-%m-%d')) - (time1 | to_datetime('%Y-%m-%d')) }}"


     - debug:
         msg: 
           - "{{ diff }} {{ diff | type_debug }}"
           - "{{ time1 }} {{ time1 | type_debug }}"
           - "{{ time2 }} {{ time2 | type_debug }}"


     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play



