---
 - hosts: localhost
   tasks:
     - name: Create fact for time - fact will be AnsibleUnicode
       ansible.builtin.set_fact:
         time1: "00:00:01"

     - name: Create fact for time - fact will be AnsibleUnicode
       ansible.builtin.set_fact:
         time2: "12:00:00"
    

     - name: Calculate difference between dates
       set_fact:
         diff: "{{ (time2 | to_datetime('%H:%M:%S')) - (time1 | to_datetime('%H:%M:%S')) }}"


     - debug:
         msg: 
           - "{{ diff }}"
           - "{{ time1 | type_debug }}"
           - "{{ time2 | type_debug }}"



     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play



