---
 - hosts: localhost
   tasks:
     - name: Create fact for time - fact will be AnsibleUnicode
       ansible.builtin.set_fact:
         time1: "2024-01-01 00:00:01"

     - name: Create fact for time - fact will be dict
       ansible.builtin.set_fact:
         time2: "{{ ansible_date_time }}"

     - name: Create fact for time - fact will be AnsibleUnsafeText
       ansible.builtin.set_fact:
         time3: "{{ ansible_date_time.iso8601 |to_datetime('%Y-%m-%dT%H:%M:%SZ') }}"


     - name: Calculate difference between dates
       set_fact:
         diff: "{{ (time2 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) - (time1 | to_datetime('%Y-%m-%d %H:%M:%S')) }}"


     - debug:
         msg: 
           - "{{ diff }} {{ diff | type_debug }}"
           - "{{ time1 }} {{ time1 | type_debug }}"
           - "{{ time2 }} {{ time2 | type_debug }}"

     - name: Timmay HARD STOP this Playbook
       ansible.builtin.meta: end_play



