---
- name: Automate Ansible Execution Environment Build
  hosts: localhost

  tasks:

    - name: Create git archive from repos
      ansible.builtin.git:
        repo: "{{ build_repo }}"
        dest: "/{{ tag_name }}"


    - name: Run ansible-builder build command
      ansible.builtin.shell:
        cmd: ansible-builder build --tag "{{ tag_name }}:latest"
        chdir: "/{{ tag_name }}"
      register: build_output


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play


    - name: Create execution-environment.yml (definition file)
      ansible.builtin.copy:
        dest: /runner/timmay-prod/execution-environment.yml
        content: |
          version: 1
          dependencies:
            python: requirements.txt
            system: bindep.txt
            galaxy: requirements.yml


    - name: Run ansible-builder build command
      ansible.builtin.shell:
        cmd: |
          ansible-builder build \
          --container-runtime docker \
          --tag my-execution-environment:latest \
          --context /runner/timmay-prod/build-context
        chdir: /runner/timmay-prod/build-context
      register: build_output


    - name: Display build output
      ansible.builtin.debug:
        var: build_output.stdout


    - name: Verify the container was built successfully
      ansible.builtin.command:
        cmd: podman images my-execution-environment:latest
      register: image_check


    - name: Display the built image information
      ansible.builtin.debug:
        var: image_check.stdout_lines


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play

