---
 - hosts: localhost
   tasks:
     - name: Create fact for time - fact will be datetime object 
       ansible.builtin.set_fact:
         time1: 2024-01-01T00:00:00Z

     - name: Create fact for time - fact will be AnsibleUnicode 
       ansible.builtin.set_fact:
         time2: '2024-01-01T00:00:00Z'

     - name: Create fact for time - fact will be AnsibleUnicode 
       ansible.builtin.set_fact:
         time3: "2024-01-01T00:00:00Z"

     - name: Create fact for time - fact will be dict
       ansible.builtin.set_fact:
         time4: "{{ ansible_date_time }}"

     - name: Create fact for time - fact will be dict
       ansible.builtin.set_fact:
         time5: "{{ ansible_date_time.iso8601 }}"



     - name: Review the facts
       ansible.builtin.debug:
         msg: 
         - "time1 -- {{ time1 }} -- {{ time1 | type_debug }}"
         - "time2 -- {{ time2 }} -- {{ time2 | type_debug }}"
         - "time3 -- {{ time3 }} -- {{ time3 | type_debug }}"
         - "time4 -- {{ time4 }} -- {{ time4 | type_debug }}"         
         - "time5 -- {{ time5 }} -- {{ time5 | type_debug }}"
