---
 - hosts: localhost
   tasks:

     - name: Create fact for time1 - fact will be datetime object 
       ansible.builtin.set_fact:
         time1: 2024-01-01T00:00:00Z

     - name: Create fact for time1 - fact will be AnsibleUnicode 
       ansible.builtin.set_fact:
         time2: '2024-01-01T00:00:00Z'

     - name: Review the facts
       ansible.builtin.debug:
         msg: 
         - "time1 -- {{ time1 }} -- {{ time1 | type_debug }}"
         - "time2 -- {{ time2 }} -- {{ time2 | type_debug }}"
