---
- name: Fetch the Cert & Private Key from DocWiki Servers
  hosts: docwiki
  gather_facts: true

  tasks:

    - name: Store file into /etc/ssl/private/cert.key
      ansible.builtin.fetch:
        src: /etc/ssl/private/cert.key
        dest: docwiki-private.key


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play



    - name: Specifying a path directly
      ansible.builtin.fetch:
        src: /tmp/somefile
        dest: /tmp/prefix-{{ inventory_hostname }}
        flat: yes

    - name: Specifying a destination path
      ansible.builtin.fetch:
        src: /tmp/uniquefile
        dest: /tmp/special/
        flat: yes

    - name: Storing in a path relative to the playbook
      ansible.builtin.fetch:
        src: /tmp/uniquefile
        dest: special/prefix-{{ inventory_hostname }}
        flat: yes



