---
- name: Read a file from a linux host
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
      ansible.builtin.fetch:
        src: /tmp/somefile
        dest: /tmp/fetched


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play



    - name: Specifying a path directly
      ansible.builtin.fetch:
        src: /tmp/somefile
        dest: /tmp/prefix-{{ inventory_hostname }}
        flat: yes

    - name: Specifying a destination path
      ansible.builtin.fetch:
        src: /tmp/uniquefile
        dest: /tmp/special/
        flat: yes

    - name: Storing in a path relative to the playbook
      ansible.builtin.fetch:
        src: /tmp/uniquefile
        dest: special/prefix-{{ inventory_hostname }}
        flat: yes



