---
- name: Fetch the Cert & Private Key from DocWiki Servers
  hosts: docwiki
  gather_facts: true

#
# Next Tasks...
# 1. This should be able to be run 1x per day. 
# 2. This should not overwrite certs in Vault that are the same. 
# 3. Use OpenSSL to inspect cert in Vault and cert from website. 
# 4. Compare, only write new cert if website cert is different from Vault Cert.
#
#

  tasks:

    - name: 01 - Store file into /etc/ssl/private/cert.key
      ansible.builtin.fetch:
        src: /etc/ssl/private/cert.key
        dest: /docwiki-private.key
        flat: true        


    - name: 02 - Store file into /etc/ssl/private/cert.pem
      ansible.builtin.fetch:
        src: /etc/ssl/private/cert.pem
        dest: /docwiki.pem
        flat: true   


    - name: 02a - Read the contents of the src file
      ansible.builtin.command: cat /etc/ssl/private/cert.pem
      register: src_file


    - name: 02b - Read the contents of the dest file
      ansible.builtin.command: cat /docwiki-private.key
      delegate_to: localhost
      register: dest_file


    - name: 03 - Write Cert & Key to Vault
      delegate_to: localhost
      community.hashi_vault.vault_kv2_write:
        path: "{{ ansible_fqdn }}"
        url: "{{ vault_url }}"
        auth_method: "{{ vault_auth_method }}"
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_mount }}"
        data:
          cert: "{{ lookup('file', '/docwiki.pem') }}"
          private_key: "{{ lookup('file', '/docwiki-private.key') }}"


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play



