- name: Gather facts tasks
  hosts: all
  gather_facts: true
  gather_subset:
    - all
#  vars:
#    ansible_become_password: "{{ ansible_become_password }}"

# Gather subset options are:
#   all, network, hardware, virtual, ohai, facter, and min
# 

  tasks:
    - name: Display facts
      debug:
        var: ansible_facts
