- name: Gather minimal facts
  hosts: all
  gather_facts: true
  gather_subset:
    - virtual

# Gather subset options are:
#   all, network, hardware, virtual, ohai, facter, and min
# 

  tasks:
    - name: Display minimal facts
      debug:
        var: ansible_facts
