---
- name: Backup Cisco IOS XE Running Configuration
  hosts: iosxe
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Backup Running Configuration
      cisco.ios.ios_config:
        backup: yes
      register: config_backup

    - name: Display Backup File Path
      ansible.builtin.debug:
        msg: "Backup saved to {{ config_backup.backup_path }}"