---
- name: Run Python Script
  hosts: localhost
  connection: local
  tasks:
    - name: Execute Python script
      command: python3 hello-from-awx.py
      register: result

    - name: Display script output
      debug:
        var: result.stdout