---
- name: Test looping through interfaces with NETCONF
  hosts: iosxe
  connection: netconf
  gather_facts: false

  tasks:
  
    - name: Task to Shutdown Interface Gig1/0/1
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/1</name>
                    <shutdown xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"/>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>


    - name: Task to Shutdown Interface Gig1/0/2
      ansible.netcommon.netconf_config:
        xml: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <interface>
                  <GigabitEthernet>
                    <name>1/0/2</name>
                    <shutdown xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge"/>
                  </GigabitEthernet>
                </interface>
              </native>
            </config>


    - name: No Shut All the Interfaces in the loop
      ansible.netcommon.netconf_config:
        xml: |
          <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
              <interface>
                <{{ item.type }}>
                  <name>{{ item.number }}</name>
                  <shutdown xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="delete"/>
                </{{ item.type }}>
              </interface>
            </native>
          </config>
      loop:
        - { type: "GigabitEthernet", number: "1/0/1" }
        - { type: "GigabitEthernet", number: "1/0/2" }
#        - { type: "TenGigabitEthernet", number: "1/0/1" }


