---
- name: Send a Test Message through Webex
  hosts: localhost
  gather_facts: true
  connection: local
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"

  tasks:
   - name: 01 - Retrieve Webex API Auth Info from Vault - New Cred
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "webex_token"
      auth_method: token
#      token: "{{ ansible_password }}"
      token: "{{ vault_token }}"
     register: webex_auth

   - name: XX - Cisco Webex Teams - Send Markdown Message to a Room
     community.general.cisco_webex:
      recipient_type: roomId
      recipient_id: "{{ webex_auth.data.data.space_id }}"
      msg_type: markdown
      personal_token: "{{ webex_auth.data.data.awx_report_bot }}"
      msg: "Current Time is {{ ansible_facts.date_time.time }}"
    
# this is a test

   - name: HARD STOP
     ansible.builtin.meta: end_play
