---
- name: This Playbook will get a Cloudflare A Record
  hosts: localhost
  gather_facts: false
  vars:
    vault_url: "https://vault.theglens.net:8200"
    vault_mount: "kv"
    vault_secret: "homenet_inet_ip"

  tasks:

   - name: 01 - Read Cloudflare API Token from Vault
     community.hashi_vault.vault_kv2_get:
       url: "{{ vault_url }}"
       engine_mount_point: "{{ vault_mount }}"
       path: cloudflare_token
       auth_method: token
       token: "{{ ansible_password }}"
     register: cloudflare_token

   - name: 02 - Delete a record using api token
     community.general.cloudflare_dns:
       zone: theglens.net
#       zone: c86f9eea9929c4a2fe0a6c7a9836e33b
       record: test
       state: absent
       api_token: "{{ cloudflare_token.data.data.api_key }}"

   - name: 03 - Create a record using api token
     community.general.cloudflare_dns:
       zone: theglens.net
       record: test
       type: A
       value: 51.51.51.51
       api_token: "{{ cloudflare_token.data.data.api_key }}"

