---
- name: This Playbook will create a new Cloudflare DNS record
  hosts: localhost
  gather_facts: false
  vars:
    fqdn: test-record.theglens.net
    ip_addr: "51.51.51.51"


  tasks:

    - name: 01 - Create A record with New IP address
      community.general.cloudflare_dns:
        api_token: "{{ cloudflare_api_key }}"
        record: "{{ fqdn }}"
        type: A
        value: "{{ ip_addr }}"
        state: present    # present (default), absent
        zone: theglens.net
      register: cloudflare_dns_record_create


    - name: 02 - Pause the Playbook for 20 seconds
      ansible.builtin.pause:
        seconds: 20





    - name: 01 - Create A record with New IP address
      community.general.cloudflare_dns:
        api_token: "{{ cloudflare_api_key }}"
        record: test-record
        type: A
        value: "{{ ip_addr }}"
        state: present    # present (default), absent
        zone: theglens.net
      register: response


    - name: 02 - Display the results
      ansible.builtin.debug:
        var: cloudflare_dns_record_create


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play
