---
- name: Create a DNS TXT record with the DNS-01 Challenge Text
  hosts: localhost
  gather_facts: false
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"



- tasks:
   - name: 01 - Read The NameCheap API Key from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "namecheap_api_key"
      auth_method: token
      token: "{{ ansible_password }}"
     register: namecheap_auth



   - name: HARD STOP
     ansible.builtin.meta: end_play

#
#   - name: 02 - Create DNS TXT record with NameCheap API
#     namecheap_dns_txt:
#       api_user: "{{ namecheap_api_user }}"
#       api_key: "{{ namecheap_api_key }}"
#       client_ip: "{{ namecheap_client_ip }}"
#       domain: "{{ namecheap_domain }}"
#       host: "_acme-challenge"
#       record_type: "TXT"
#       value: "{{ acme_challenge }}"
#       state: present
#     register: dns_txt_record
#
#

