---
- name: Send a Test Message through Webex
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"
   person_email: "timmayglen@gmail.com"
   webex_space_id: "61a0ac00-6ec0-11ee-8592-a1a23a6e2715"

  tasks:

   - name: 01 - Read The Webex API Auth Info from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: webex-token
      auth_method: token
      token: "{{ ansible_password }}"
     register: webex_auth



   - name: Cisco Webex Teams - Markdown Message to a Room
     community.general.cisco_webex:
      recipient_type: roomId
      recipient_id: "{{ webex_space_id }}"
      msg_type: markdown
      personal_token: "{{ webex_auth.data.data.bot_access_token }}"
      msg: "**Cisco Webex Teams Ansible Module - Room Message in Markdown**"


   - name: HARD STOP
     ansible.builtin.meta: end_play



   - name: Cisco Webex Teams - Text Message by an Individuals E-Mail Address
     community.general.cisco_webex:
      recipient_type: toPersonEmail
      recipient_id: "{{ person_email }}"
      msg_type: text
      personal_token: "{{ webex_auth.data.data.bot_access_token }}"
      msg: "Cisco Webex Teams Ansible Module - Text Message to Individual by E-Mail"



   - name: Cisco Webex Teams - Text Message by a Room ID
     community.general.cisco_webex:
      recipient_type: roomId
      recipient_id: "{{ room_id }}"
      msg_type: text
      personal_token: "{{ xxxx }}"
      msg: "Cisco Webex Teams Ansible Module - Text Message to Room by Room ID"

