---
- name: This Playbook will create a new Cloudflare DNS record
  hosts: localhost
  gather_facts: false
  vars:
    fqdn: test-record.timslab.fun
    ip_addr: "51.51.51.51"


  tasks:

    - name: 01 - Create A record with New IP address
      community.general.cloudflare_dns:
        api_token: "{{ cloudflare_api_key }}"
        record: "{{ fqdn }}"
        type: A
        value: "{{ ip_addr }}"
        state: present    # present (default), absent
        zone: timslab.fun
      register: cloudflare_dns_record_create


    - name: 02 - Display the results
      ansible.builtin.debug:
        var: cloudflare_dns_record_create


    - name: 03 - Pause the Playbook
      ansible.builtin.pause:
        seconds: 20


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play


      #tshoot task04
    - name: 04 - Delete A record with New IP address
      community.general.cloudflare_dns:
        api_token: "{{ cloudflare_api_key }}"
        record: test-record
        type: A
        value: "{{ ip_addr }}"
        state: absent    # present (default), absent
        zone: theglens.net
      register: cloudflare_dns_record_delete


    - name: Delete the record
      community.general.cloudflare_dns:
        # record is NOT here... like ok.
        zone: example.net
        type: CNAME
        value: example.com
        #account_email: test@example.com
        #account_api_key: dummyapitoken
        #state: absent



    - name: 05 - Display the results
      ansible.builtin.debug:
        var: cloudflare_dns_record_create


    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play
