---
- name: 1 - Send a Test Message through Webex
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"

  tasks:
   - name: 01 - Retrieve Webex API Auth Info from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "webex_token"
     register: webex_auth

   - name: 02 - Cisco Webex Teams - Send ISO8601 Date Time Message
     community.general.cisco_webex:
      recipient_type: roomId
      recipient_id: "{{ webex_auth.data.data.space_id }}"
      msg_type: markdown
      personal_token: "{{ webex_auth.data.data.awx_report_bot }}"
      msg: "{{ ansible_facts.date_time.iso8601 }}"

   - name: HARD STOP
     ansible.builtin.meta: end_play


