---
- name: Send a Test Message from Webex
  hosts: localhost
  gather_facts: false

  vars:
   vault_url: "https://vault.theglens.net:8200"
   vault_mount: "kv"

- tasks:
   - name: 01 - Read The Webex API Key from Vault
     community.hashi_vault.vault_kv2_get:
      url: "{{ vault_url }}"
      engine_mount_point: "{{ vault_mount }}"
      path: "webex_token"
      auth_method: token
      token: "{{ ansible_password }}"
     register: webex_auth

   - name: Print the Webex API Key
     ansible.builtin.debug:
      var: namecheap_auth

   - name: HARD STOP
     ansible.builtin.meta: end_play


   - name: Cisco Webex Teams - Text Message by an Individuals E-Mail Address
     community.general.cisco_webex:
       recipient_type: toPersonEmail
       recipient_id: "{{ timmayglen@gmail.com }}"
       msg_type: text
       personal_token: "{{ token }}"
       msg: "Cisco Webex Teams Ansible Module - Text Message to Individual by E-Mail"




#
#   - name: 02 - Create DNS TXT record with NameCheap API
#     namecheap_dns_txt:
#       api_user: "{{ namecheap_api_user }}"
#       api_key: "{{ namecheap_api_key }}"
#       client_ip: "{{ namecheap_client_ip }}"
#       domain: "{{ namecheap_domain }}"
#       host: "_acme-challenge"
#       record_type: "TXT"
#       value: "{{ acme_challenge }}"
#       state: present
#     register: dns_txt_record
#
#

