---
- name: Update and Upgrade Ubuntu Systems
  hosts: ubuntu_servers
  become: true  # Runs tasks as sudo
  tasks:

    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist  # Equivalent to 'apt full-upgrade'
        autoremove: yes
        autoclean: yes

    - name: Check if a reboot is required
      register: reboot_required
      stat:
        path: /var/run/reboot-required
        get_md5: no

    - name: Reboot the system if needed
      reboot:
      when: reboot_required.stat.exists