---
- name: Upgrade Cisco Catalyst 9300 IOS XE
  hosts: iosxe
  gather_facts: no
  connection: network_cli

  tasks:
    - name: 01 - Remove existing boot system configuration
      cisco.ios.ios_config:
        lines:
          - no boot system

    - name: 02 - Set new boot system image
      cisco.ios.ios_config:
        lines:
          - "boot system {{ boot_image_path }}"

#    - name: Exit config mode
#      cisco.ios.ios_command:
#        commands:
#          - end

    - name: 03 - Save the running configuration
      cisco.ios.ios_command:
        commands:
          - write memory

#    - name: 04 - Erase startup configuration
#      cisco.ios.ios_command:
#        commands:
#          - write erase
#      register: erase_output

#   this is from the example
    - name: Run commands that require answering a prompt
      cisco.ios.ios_command:
        commands:
          - command: "clear counters GigabitEthernet2"
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: "y"
          - command: "clear counters GigabitEthernet3"
            prompt: "[confirm]"
            answer: "\r"


    - name: Confirm erase operation
      cisco.ios.ios_command:
        commands:
          - command: write erase
          - prompt: [confirm]
          - answer: y

    - name: Reload the switch
      cisco.ios.ios_command:
        commands:
          - reload
      register: reload_output

    - name: Confirm reload operation
      cisco.ios.ios_command:
        commands:
          - y
      when: "'[confirm]' in reload_output.stdout"