---
- name: Upgrade Cisco Catalyst 9300 IOS XE
  hosts: iosxe
  gather_facts: no
  connection: network_cli

  tasks:

    - name: 01 - Remove existing boot system configuration
      cisco.ios.ios_config:
        lines:
          - no boot system


    - name: 02 - Set new boot system image
      cisco.ios.ios_config:
        lines:
          - "boot system {{ boot_image_path }}"


    - name: 03 - Save the running configuration
      cisco.ios.ios_command:
        commands:
          - write memory


    - name: 04 - Write erase the config so the switch comes up clean & ZTP
      cisco.ios.ios_command:
        commands:
          - command: "write erase"
            prompt: "[confirm]"
            answer: "y"


    - name: Reload the Catalyst 9300 switch
      cisco.ios.ios_command:
        commands:
          - command: "reload"
            prompt: "Save\\? \\[yes/no\\]:"
            answer: "no"
          - command: ""
            prompt: "Proceed with reload\\? \\[confirm\\]"
            answer: "\n"
            


