---
- name: Upgrade or Downgrade IOS XE versions in Bundle Mode
  hosts: iosxe
  gather_facts: false
  connection: network_cli

  tasks:

    - name: 01 - Remove existing boot system configuration
      cisco.ios.ios_config:
        lines:
          - no boot system


    - name: 02 - Set new boot system image
      cisco.ios.ios_config:
        lines:
          - "boot system {{ boot_image_path }}"
        # - "boot system flash:cat9k_iosxe.16.12.04.SPA.bin"

# This needs more testing,  may force a switch to not look for ZTP
#    - name: 03 - Ignore Any Startup Config
#      cisco.ios.ios_config:
#        commands:
#          - system ignore startupconfig switch all


    - name: 04 - Save the running configuration
      cisco.ios.ios_command:
        commands:
          - write memory


    - name: 05 - Write erase the config so the switch comes up clean & ZTP
      cisco.ios.ios_command:
        commands:
          - command: "write erase"
            prompt: "[confirm]"
            answer: "y"

# This worked
#    - name: Reload the XE device
#      cisco.ios.ios_command:
#        commands:
#          - command: "reload"
#            prompt: "Proceed with reload\\? \\[confirm\\]"
#            answer: "\n"

    - name: Reload the XE device
      cisco.ios.ios_command:
        commands:
          - command: "reload"
            prompt:
              - "Save?"
              - "confirm"
            answer:
              - "y"
              - "y"


